Braz-5: Create user endpoint
italoservio/braz_ecommerce pull request #13
Opened 2024-02-08 16:15 UTC by mhmBraz

2024-02-08 21:47 UTC, italoservio requested changes

2024-02-09 13:54 UTC, mhmBraz commented on services/users/infra/http/user_validator_controller.go
> +}
https://github.com/italoservio/braz_ecommerce/pull/13/commits/7780cc3833a28127e4375285a0bff8680c256ffa

2024-02-09 13:55 UTC, mhmBraz commented on services/users/infra/http/user_controller_test.go
> +		bodyReader := strings.NewReader(`{"Username": "12124", "Password": "testinasg", "Channel": "M"}`)
https://github.com/italoservio/braz_ecommerce/pull/13/commits/3900a0a786cb79635c675464838bf9dfaa27ad70

2024-02-09 13:55 UTC, mhmBraz commented on services/users/infra/http/user_controller_test.go
> +		bodyReader := strings.NewReader(`{"first_name": "testinasg", "last_name": "testinasg", "email": "testinasg", "type": "testinasg", "password": "testinasg"}`)
https://github.com/italoservio/braz_ecommerce/pull/13/commits/3900a0a786cb79635c675464838bf9dfaa27ad70

2024-02-09 13:55 UTC, mhmBraz commented on services/users/infra/http/user_controller_test.go
> +		bodyReader := strings.NewReader(`{"first_name": "testinasg", "last_name": "testinasg", "email": "testinasg", "type": "testinasg", "password": "testinasg"}`)
https://github.com/italoservio/braz_ecommerce/pull/13/commits/3900a0a786cb79635c675464838bf9dfaa27ad70

2024-02-09 13:55 UTC, mhmBraz commented on services/users/app/create_user.go
> +	}
https://github.com/italoservio/braz_ecommerce/pull/13/commits/46bf56b3e2e6795b83d8cc2cec8d0f830009378b

2024-02-09 13:55 UTC, mhmBraz commented on packages/exception/http_exception.go
> +		response.ErrorMessage = "Invalid input for one or more required attributes"
https://github.com/italoservio/braz_ecommerce/pull/13/commits/ac0ee704ea8cb45169a0610e710ee65cc1c4ca8f

2024-02-09 13:55 UTC, mhmBraz commented on packages/encryption/encrypt.go
> +	}
https://github.com/italoservio/braz_ecommerce/pull/13/commits/d8e9e64c1308baf013bc8d2948bd5d234ec0ec19

2024-02-09 15:17 UTC, italoservio approved these changes

2024-02-15 17:29 UTC, merged