Braz-6 Update user endpoint
italoservio/braz_ecommerce pull request #18
Opened 2024-02-24 03:06 UTC by mhmBraz

### Ticket: [BRAZ-](https://servioitalo.atlassian.net/browse/BRAZ-)

### This PR will:
-

2024-02-24 05:11 UTC, mhmBraz commented on services/users/app/update_user.go
> +		fmt.Printf("%v", err)
estava dando erro, pois não estava usando o err em outro lugar.

2024-02-24 17:03 UTC, italoservio requested changes

2024-02-24 17:03 UTC, italoservio commented on services/users/app/update_user.go
> +	}
Completamente desnecessário fazer duas queries no banco de dados. A função `UpdateById` tem que retornar o registro mais atual.

2024-02-26 11:33 UTC, mhmBraz commented on cmd/users/main.go
> +	usersV1.Patch("/:id", userController.UpdateUser)
https://github.com/italoservio/braz_ecommerce/pull/18/commits/cf68e0651835e260b0c1e97366432a06e579b060

2024-02-26 12:10 UTC, mhmBraz commented on packages/database/crud_repository.go
> +func (cr *CrudRepository) GetByEmail(
https://github.com/italoservio/braz_ecommerce/pull/18/commits/2256bdddd988bc6a59f14c1f90a5dbaa0fe84425

2024-02-26 12:13 UTC, mhmBraz commented on packages/exception/http_exception.go
> +		response.StatusMessage = "Not have permission"
https://github.com/italoservio/braz_ecommerce/pull/18/commits/e7787c9cca7780c0058da41e4435525e4c87d157

2024-02-26 12:24 UTC, mhmBraz commented on services/users/app/create_user_test.go
> +	updateUserImpl     *app.UpdateUserImpl
https://github.com/italoservio/braz_ecommerce/pull/18/commits/c3a226b862e96a33ef9ee71e34d2bb0de7263940

2024-02-26 12:31 UTC, mhmBraz commented on services/users/infra/http/user_controller.go
> +	}, id, app.UpdateUserOutput{})
https://github.com/italoservio/braz_ecommerce/pull/18/commits/3c1670c5b0fc28d198a943e5799e38c04ad99522

2024-02-26 12:31 UTC, mhmBraz commented on services/users/infra/http/user_controller.go
> +	}, id, app.UpdateUserOutput{})
pra o mock app.UpdateUserOutput{}

2024-03-02 05:50 UTC, italoservio commented on packages/database/crud_repository_test.go
> +		defer nestedMt.ClearMockResponses()
@mhmBraz mock do `findOneAndUpdate`

2024-03-02 05:51 UTC, italoservio commented on packages/database/crud_repository_test.go
> +		defer nestedMt.ClearMockResponses()
quando acabar o restante me fale que eu olho denovo

2024-03-03 00:09 UTC, italoservio commented on packages/exception/http_exception.go
> +		response.StatusMessage = "Not have permission"
Se alterou para "403 Forbidden" a StatusMessage deve ser "Forbidden" e não "Unauthorized"

2024-03-05 11:48 UTC, mhmBraz commented on packages/exception/http_exception.go
> +		response.StatusMessage = "Not have permission"
https://github.com/italoservio/braz_ecommerce/pull/18/commits/830768004d2dc70db805d3f68f9bc53d68f626ef

2024-03-05 11:51 UTC, mhmBraz commented on services/users/app/update_user.go
> +	Do(ctx context.Context, updateUser *UpdateUserInput, id string, output UpdateUserOutput) (*UpdateUserOutput, error)
https://github.com/italoservio/braz_ecommerce/pull/18/commits/8db53118659d2a1eb5d2333082d8296e3437a05e

2024-03-05 11:53 UTC, mhmBraz commented on services/users/infra/http/user_controller.go
> +	"log/slog"
https://github.com/italoservio/braz_ecommerce/pull/18/commits/0963864dd2b8ab27d93248c2cbace4986b502748

2024-03-05 11:53 UTC, mhmBraz commented on services/users/infra/http/user_controller.go
> -
Só tinha mudado de lugar, mas voltamos

2024-03-05 11:53 UTC, mhmBraz commented on services/users/app/update_user.go
> +func (gu *UpdateUserImpl) Do(ctx context.Context, updateUser *UpdateUserInput, id string, output UpdateUserOutput) (*UpdateUserOutput, error) {
ok

2024-03-05 11:54 UTC, mhmBraz commented on services/users/app/update_user.go
> +
ok

2024-03-05 11:54 UTC, mhmBraz commented on services/users/app/update_user.go
> +		fmt.Printf("%v", err)
ok

2024-03-06 00:52 UTC, italoservio approved these changes

2024-03-06 00:53 UTC, merged