BRAZ-35: Stop bringing deleted rows from the database
italoservio/braz_ecommerce pull request #21
Opened 2024-03-11 03:04 UTC by mhmBraz

### Ticket: [BRAZ-](https://servioitalo.atlassian.net/browse/BRAZ-)

### This PR will:
-

2024-03-13 01:19 UTC, italoservio requested changes
o que são essas alterações em 
createUser
updateUserById
?

2024-03-13 01:19 UTC, italoservio commented on services/users/app/get_user_paginated.go
>  	input *GetUserPaginatedInput,
deleted deve fazer parte do input

2024-03-13 01:19 UTC, italoservio commented on services/users/app/get_user_paginated.go
> +	fmt.Printf("%v", filters)
remover

2024-03-13 01:19 UTC, italoservio commented on services/users/infra/http/user_controller.go
> +type GetUserPayload struct {
renomear
```suggestion
type GetUserByIdPayload struct {
```

2024-03-13 01:19 UTC, italoservio commented on services/users/infra/http/user_controller.go
> +	}
precisamos realmente validar o query param?

2024-03-13 01:19 UTC, italoservio commented on services/users/infra/http/user_controller.go
> +	}
precisamos realmente validar o query param nesse caso?

2024-03-13 01:19 UTC, italoservio commented on services/users/app/get_user_by_id.go
> +func (gu *GetUserByIdImpl) Do(ctx context.Context, id string, deleted bool) (*GetUserByIdOutput, error) {
criar um input que armazena ambos valores
```go
type GetUserByIdInput struct {
  Id      string
  Deleted bool
}
```

2024-03-13 01:22 UTC, italoservio commented on packages/database/crud_repository.go
> +		options.FindOneAndUpdate().SetReturnDocument(options.After),
Top demais! :fire:

2024-03-14 02:45 UTC, mhmBraz commented on services/users/app/get_user_paginated.go
>  	input *GetUserPaginatedInput,
https://github.com/italoservio/braz_ecommerce/pull/21/commits/fb7534abe448f9882408e14993b756dcb5d1222e

2024-03-14 02:47 UTC, mhmBraz commented on services/users/infra/http/user_controller.go
> +type GetUserPayload struct {
https://github.com/italoservio/braz_ecommerce/pull/21/commits/7aaf27b051d025ef18c02ee8c4e1dfdad4438c6d

2024-03-14 02:47 UTC, mhmBraz commented on services/users/infra/http/user_controller.go
> +	}
é bom

2024-03-19 02:03 UTC, italoservio approved these changes

2024-03-19 02:04 UTC, merged